default: &default
  adapter: postgresql
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MainYourMom_development

test:
  <<: *default
  database: MainYourMom_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  host: <%=ENV['$OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port: <%=ENV['$OPENSHIFT_POSTGRESQL_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
