default: &default
  adapter: postgresql
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MainYourMom_development

test:
  <<: *default
  database: MainYourMom_test

production:
  <<: *default
  database: MainYourMom_production
